export const en = {
    // Short phrases/headers
    /* 
    identifier: 'Identifier',
    iscte_user: 'Iscte User',
    email_details: 'Email Details',
    from: 'From',
    subject: 'Subject',
    to: 'To',
    body: 'Body',
    status: 'Status',
    request_date: 'Request Date',
    attachments: 'Attachments',
    priority: 'Priority',
    email_list: 'Email List',
    smses_list: 'Smses List',
    creation_date: 'Creation Date',
    no: 'No',
    yes: 'Yes',
    confirmation: 'Confirmation',
    create_api_user: 'Create API User',
    submit: 'Submit',
    sms_detail: 'SMS Detail',
    resources: 'Resources',
    api_users: 'API Users',
    emails: 'Emails',
    smses: 'Smses',
    roles: 'Roles',
    api_user_details: 'API User Details',
    personal_profile: 'Personal Profile',
    switch_role: 'Switch Role',
    profile: 'Profile',
    change_user_roles: 'Change User Roles',
    user_roles: 'User Roles',
    api: 'API',
    dispatches: 'Dispatches',
    jobs: 'Jobs',
    personal_area: 'Personal Area',
    change_profile: 'Change Profile',
    change_role: 'Change Role',
    api_user: 'API User',
    code: 'Code',
    periodicity: 'Periodicity',
    resource_limit: 'Resource Limit',
    last_run: 'Last Run',
    last_status: 'Last Status',
    last_run_status: 'Last Run Status',
    request_status: 'Request Status',
    email_dispatch_history: 'Email Dispatch History',
    sms_dispatch_history: 'SMS Dispatch History',
    date: 'Date',
    error: 'Error',
    name: 'Name',
    processed_date: 'Dispatch run date',
    requests_processed: 'Requests processed',
    menu: 'Menu',
    requests: 'requests',
    edit_job: 'Edit job',
    job_details: 'Job details',

    // Switch words/phrases
    priorityNames: {
        1: 'Low',
        2: 'High',
        3: 'Highest',
    },
    apiUserStatus: {
        'active': 'Active',
        'disabled': 'Disabled',
    },

    // Sentences
    no_email_requests_found: 'No email requests found',
    no_sms_requests_found: 'No SMS requests found',
    no_email_dispatches_found: 'No email dispatches found',
    no_sms_dispatches_found: 'No SMS dispatches found',
    copy_password: 'Copy password',
    request_new_password: 'Request new password',
    no_api_users_found: 'No API users found',
    this_field_is_required: 'This field is required',
    disable_api_user: 'Disable API user',
    enable_api_user: 'Enable API user',
    manage_api_users: 'Manage API users',
    search_users: 'Search users',
    no_run_made: 'No run made',
    add_role_to_user: 'Add role to user',
    dispatch_details: 'Dispatch details',
    dispatch_history: 'Dispatch history',
    edit_dispatch: 'Edit dispatch',
    save: 'Save',
    sms_requests_list: 'SMS requests list',
    email_requests_list: 'Email requests list',
    sms_request_details: 'SMS request details',
    email_request_details: 'Email request details',
    last_dispatch_history: 'Last dispatch history',
    sms_dispatches_list: 'SMS dispatches list',
    email_dispatches_list: 'Email dispatches list',
    sms_dispatch_details: 'SMS dispatch details',
    email_dispatch_details: 'Email dispatch details',
    last_dispatch_status: 'Last dispatch status',
    check_request: 'Check request',
    check_dispatch: 'Check dispatch',
    latest_dispatch_history: 'Latest dispatch history',
    job_history: 'Job history',
    job_has_no_history: 'Job doesn\'t have a history',
    email_has_no_history: 'Email doesn\'t have a history',
    sms_has_no_history: 'SMS doesn\'t have a history',
    no_dispatch_found: 'No dispatch found',
    edit_allowed_ips: 'Edit allowed IPs',
    allowed_ips: 'Allowed IPs',
    all: 'All',
    actions: 'Actions',
    ips: 'IPs',
    expiration_date: 'Expiration date',
    never: 'Never',
    new_password: 'New password',
    access_interval: 'Access interval',
    start_date: 'Start date',
    end_date: 'End date',
    open_to_all_ips: 'Open to all IPs',
    manage_users: 'Manage users',
    users: 'Users',
    apiUser: 'API User',
    dates: 'Dates',
    search: 'Search',

    // Page specific strings
    apiUserDetail: {
        change_password_confirmation_text: 'Request to change the password of this entity will stop the API from making requests with its old password. Are you sure?',
    },
    createApiUser: {
        identifier_min_length_warning: 'Identifier should have a minimum length of 3.',
        identifier_already_exists_warning: 'An API user already exists with this name.',
    },
    apiJobs: {
        jobs_not_found: 'No jobs were found.',
    },
    ApiJobDetail: {
        check_periodicity_pattern: 'Check if the pattern is correct. It should start with numbers followed by:',
        check_job_resource_limit: 'Check if you inserted a number.'
    },
    */
    test_environment: 'Test environment',
    menu: 'Menu',
    TopBar: {
        imageTag: 'en',
        title1: 'Notification',
        title2: 'Center'
    }
};
