export const pt = {
    // Short phrases/headers
    /* identifier: 'Identificador',
    iscte_user: 'Utilizador Iscte',
    email_details: 'Detalhe de Email',
    from: 'De',
    subject: 'Assunto',
    to: 'To',
    body: 'Corpo',
    status: 'Estado',
    request_date: 'Data do Pedido',
    attachments: 'Anexos',
    priority: 'Prioridade',
    email_list: 'Lista de Emails',
    smses_list: 'Lista de Smses',
    creation_date: 'Data de Criação',
    no: 'Não',
    yes: 'Sim',
    confirmation: 'Confirmation',
    create_api_user: 'Criar Utilizador API',
    submit: 'Submeter',
    sms_detail: 'Detalhes do SMS',
    resources: 'Recursos',
    api_users: 'Utilizadores API',
    emails: 'Emails',
    smses: 'Smses',
    roles: 'Perfis',
    api_user_details: 'Detalhe Utilizador API',
    personal_profile: 'Perfil Pessoal',
    switch_role: 'Mudar de Perfil',
    profile: 'Perfil',
    change_user_roles: 'Mudar Perfis',
    user_roles: 'Perfis de Utilizadores',
    api: 'API',
    dispatches: 'Envios',
    jobs: 'Trabalhos',
    personal_area: 'Área Pessoal',
    change_profile: 'Mudar de Perfil',
    change_role: 'Mudar Estatuto',
    api_user: 'Utilizadores API',
    code: 'Código',
    periodicity: 'Periodicidade',
    resource_limit: 'Limite Recursos',
    last_run: 'Ultima Execução',
    last_run_status: 'Estado Ultima Execução',
    request_status: 'Estado do Pedido',
    email_dispatch_history: 'Historico de Envio',
    sms_dispatch_history: 'Historico de Envio',
    date: 'Data',
    error: 'Erro',
    name: 'Nome',
    processed_date: 'Data Execução',
    requests_processed: 'Pedidos Executados',
    menu: 'Menu',
    requests: 'Pedidos',
    edit_job: 'Editar Tarefa',
    job_details: 'Detalhes da Tarefa',
    job_history: 'Historico da Tarefa',
    last_status: 'Ultimo estado',

    // Switch words/phrases
    priorityNames: {
        1: 'Baixa',
        2: 'Alta',
        3: 'Altíssima',
    },
    apiUserStatus: {
        'active': 'Ativo',
        'disabled': 'Desativado',
    },

    // Sentences
    no_email_requests_found: 'Nenhum pedido de email encontrado',
    no_sms_requests_found: 'Nenhum pedido de SMS encontrado',
    no_email_dispatches_found: 'Nenhuma envio de email encontrado',
    no_sms_dispatches_found: 'Nenhuma envio de SMS encontrado',
    copy_password: 'Copiar palavra-passe',
    request_new_password: 'Pedi nova palavra-passe',
    no_api_users_found: 'Nenhum utilizador de API encontrado',
    this_field_is_required: 'Este campo é necessário',
    disable_api_user: 'Desactivar utilizador API',
    enable_api_user: 'Activar utilizador API',
    manage_api_users: 'Gerir utilizadores API',
    search_users: 'Procurar utilizadores',
    no_run_made: 'Nenhuma execução feita',
    add_role_to_user: 'Adicionar perfil ao utilizador',
    dispatch_details: 'Detalhes do envio',
    dispatch_history: 'Historico do envio',
    save: 'Guardar',
    test_environment: 'Ambiente de testes',
    sms_requests_list: 'Lista de pedidos de SMS',
    email_requests_list: 'Lista de pedidos de emails',
    sms_request_details: 'Detalhes do pedido de SMS',
    email_request_details: 'Detalhes do pedido de email',
    sms_dispatches_list: 'Lista de tarefas de SMS',
    email_tasks_list: 'Lista de tarefas de email',
    last_dispatch_history: 'Ultimo historico do envio',
    sms_dispatch_details: 'Detalhes da tarefa de SMS',
    email_dispatch_details: 'Detalhes do envio do Email',
    last_task_status: 'Estado ultima tarefa',
    check_request: 'Ver pedido',
    check_dispatch: 'Ver envio',
    email_dispatches_list: 'Lista de envios de email',
    latest_dispatch_history: 'Historico mais recente do envio',
    last_dispatch_status: 'Ultimo historico do envio',
    latest_task_history: 'Historico mais recente da tarefa',
    email_has_no_history: 'O email não tem historico',
    sms_has_no_history: 'O SMS não tem historico',
    job_has_no_history: 'A tarefa não tem historico',
    no_dispatch_found: 'Nenhum envio encontrado',
    edit_allowed_ips: 'Editar IPs permitidos',
    allowed_ips: 'IPs permitidos',
    all: 'Todos',
    actions: 'Ações',
    ips: 'IPs',
    expiration_date: 'Data de expiração',
    never: 'Nunca',
    new_password: 'Nova palavra-passe',
    access_interval: 'Intervalo de acesso',
    start_date: 'Data inicio',
    end_date: 'Data fim',
    open_to_all_ips: 'Aberto a todos os IPs',
    manage_users: 'Gerir utilizadores',
    users: 'Utilizadores',
    apiUser: 'Utilizador API',
    dates: 'Datas',
    search: 'Pesquisa',

    // Page specific strings
    apiUserDetail: {
        change_password_confirmation_text: 'Pedir para mudar a palavra-passe desta entidade irá impedir da API realizar pedidos com a password antiga. Tem a certeza?',
    },
    createApiUser: {
        identifier_min_length_warning: 'Identificador deve de ter pelo menos 3 letras.',
        identifier_already_exists_warning: 'Já existe um utilizador API com este nome.',
    },
    apiJobs: {
        jobs_not_found: 'Nenhum trabalho encontrado.',
    },
    ApiJobDetail: {
        check_periodicity_pattern: 'Verifique se o padrão está correto. Deve de conter números seguido por:',
        check_job_resource_limit: 'Verifique se inseriu um número.'
    },
    */
    TopBar: {
        imageTag: 'pt',
        title1: 'Centro',
        title2: 'Notificações'
    },
    test_environment: 'Ambiente de testes',
    menu: 'Menu',
};
